### ISSUE TITLE
hasMany 'users' errors with "Collection named 'users' has not been defined"

### ISSUE THREAD

**Issue by johndevor** [emmerge/graviton#5]
In this example below, I'm unable to get a 'hasMany' relationship with Meteor's users collection. 

```
ChatModel = Graviton.Model.extend({
  hasMany: {
    users: {
      collectionName: 'users',
      foreignKey: 'chatId'
    }
  },
  belongsToMany: {
    users: {
      collectionName: 'users',
      field: 'userIds'
    }
  }
}, { });

Chat = Graviton.define("chats2", {
  modelCls: ChatModel
});

var c = Chat.create({ }); // This command errors
```

The resulting error is:

```
"Collection named 'users' has not been defined"
```

Kind of a Meteor newbie here, so I apologize if this is entirely obvious.

**Comment by johndevor** [comment]
It's confusing to me, as there already seems to be the collection named 'users':

```
Mongo.Collection {_makeNewID: function, _transform: function, _connection: Connection, _collection: LocalCollection, _name: "users"…}
```

**Comment by johndevor** [comment]
Ok, it turns out that it's an error with the Houston (admin) package. Installing that packages changes the instanceof result of Meteor.users when it shouldn't.

Here's the issue I posted on that project about it:

https://github.com/gterrono/houston/issues/283

**Comment by johndevor** [comment]
This model format ended up working for me:

```
ChatModel = Graviton.Model.extend({
  hasMany: {
    users: {
      collection: Meteor.users,
      foreignKey: 'chatId'
    }
  },
  belongsToMany: {
    users: {
      collection: Meteor.users,
      field: 'userIds'
    }
  }
}, { });

Chat = Graviton.define("chats2", {
  modelCls: ChatModel
});
```

**Comment by mhwheeler** [comment]
I can reproduce this without Huston.

You've figured out one solution: Using `collection: Meteor.users` instead of `collectionName: 'users'` to define the model is definitely the simplest fix to this.

Another good fix is to define the user collection within Graviton: `Graviton.define('users');` If you do that you can use `collectionName` references to `users`. This is the correct approach if you want to make a model out of users or have relations defined on users.

I'm going to re-open this issue because, at the very least, the error `Collection named 'users' has not been defined` is not clear that the collections need to be defined in Graviton, not just Meteor.

**Comment by johndevor** [comment]
Is there an example of using Graviton to define relationships on top of the
Meteor.users collection? It's all kind of confusing and hairy for me being
an ex django guy.

**Comment by mhwheeler** [comment]
Yeah! Examples totally needed. Here's a simple relationship between a collection and the user collection. Note that we don't transform the user object returned by Meteor.user() because we don't want to interfere with the behavior of other packages. We also would not tranform the result of `GravitonUsers.findOne()` for similar reasons. To get the user model you manually `build()`.

#### Defintions
```javascript
ChatModel = Graviton.Model.extend({
  belongsTo: {
    user: {
      collectionName: 'users',
      field: 'userId'
    }
  }
}, {});

Chats = Graviton.define("chats", {
  modelCls: ChatModel
});

UserModel = Graviton.Model.extend({
  hasMany: {
    chats: {
      collectionName: 'chats'
    }
  }
}, {});

GravitonUsers = Graviton.define('users', {
  modelCls: UserModel
});
```

#### Use
```javascript
// create a chat entry that belongs to the user
ChatBelongsToUser.create({userId: Meteor.userId(), topic: 'user chat'});

// find all chats that belong to the user
GravitonUsers.build(Meteor.user()).chats.find();

// find the user for a chat belongs to (note: returns user object not model)
Chats.findOne({topic: 'user chat'}).user();
```

**Comment by johndevor** [comment]
Thanks, great answer! A couple other questions if you have time:

* How does the data validation provided by collection2 fit into the picture? 
* Why are so few people using Graviton? Seems like a good and necessary package and I haven't found other decent alternatives other than minimongoid (I'm not sure how kosher that package is...).

Much appreciated.

**Comment by johndevor** [comment]
To answer my own question, it looks like some people use collection-hooks to validate the data:
https://github.com/matb33/meteor-collection-hooks/

**Comment by mhwheeler** [comment]
Have not tried collection2 so cannot comment. We use collection-hooks and it plays nicely.

We have not spread the word about Graviton at all yet, the only uptake has been through atmosphere. We've been developing it for ourselves mostly. To take it to the next level we need to:

* Complete more of the doc
* Give more/better example code in the doc
* Make Graviton powered versions of standard meteor example apps (leaderboard, todos)
* Update Graviscope, a Graviton powered version of Discover Meteor's "Telescope" (this was complete and working but Telescope has change an awful lot since then)
* Introduce it to the community in a Meteor Devshop Lightning Talk

**Comment by mhwheeler** [comment]
Also made a section in the doc: 1c78e4be11f65f3963dd362b45adb6110e76212e

**Comment by johndevor** [comment]
Thanks! Looking good. I'll try to contribute once I get the hang of all
this... if that ever happens. :)
